# Generated by Django 6.0 on 2026-03-04 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='expires_in',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 4, 15, 43, 18, 478694)),
            preserve_default=False,
        ),
    ]
