# Generated by Django 6.0 on 2026-03-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='sond_id',
            new_name='song_id',
        ),
    ]
