# Generated by Django 6.0 on 2026-03-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_room_current_song'),
        ('spotify', '0004_rename_sond_id_vote_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'room', 'song_id')},
        ),
    ]
